# Generated by Django 5.0 on 2024-01-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_mobile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='amazon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('image', models.ImageField(upload_to='mobile')),
            ],
        ),
    ]
