# Generated by Django 5.0 on 2024-01-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_amazon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='image',
            field=models.ImageField(upload_to='amazon'),
        ),
    ]
